; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = teensy40

[env:teensy40]
platform = teensy
board = teensy40
build_flags = -O2
build_unflags = -Os
framework = arduino
lib_deps = https://github.com/luni64/TeensyTimerTool.git
    https://github.com/PaulStoffregen/SPI.git
monitor_speed = 115200

[env:encoder_test]
src_filter = +<i2c_encoder_test.cpp>
platform = teensy
board = teensy41
build_flags = -O2
build_unflags = -Os
framework = arduino
lib_deps = https://github.com/luni64/TeensyTimerTool.git
    https://github.com/PaulStoffregen/SPI.git
monitor_speed = 115200

[env:example_i2c]
build_src_filter = +<example_i2c.cpp>
platform = teensy
board = teensy41
build_flags = -O2
build_unflags = -Os
framework = arduino
lib_deps = https://github.com/luni64/TeensyTimerTool.git
    https://github.com/PaulStoffregen/SPI.git
monitor_speed = 115200


[env:spi_encoder_test]
src_filter = +<spi_encoder_test.cpp>
platform = teensy
board = teensy41
build_flags = -O2
build_unflags = -Os
framework = arduino
lib_deps = https://github.com/luni64/TeensyTimerTool.git
    https://github.com/PaulStoffregen/SPI.git
monitor_speed = 115200


[env:example_spi]
src_filter = +<example.cpp>
platform = teensy
board = teensy41
build_flags = -O2
build_unflags = -Os
framework = arduino
lib_deps = https://github.com/luni64/TeensyTimerTool.git
    https://github.com/PaulStoffregen/SPI.git
monitor_speed = 115200

[env:spi_encoder_test_40]
src_filter = +<spi_encoder_test.cpp>
platform = teensy
board = teensy40
build_flags = -O2
build_unflags = -Os
framework = arduino
lib_deps = https://github.com/luni64/TeensyTimerTool.git
    https://github.com/PaulStoffregen/SPI.git
monitor_speed = 115200

[env:example_spi_40]
src_filter = +<example.cpp>
platform = teensy
board = teensy40
build_flags = -O2
build_unflags = -Os
framework = arduino
lib_deps = https://github.com/luni64/TeensyTimerTool.git
    https://github.com/PaulStoffregen/SPI.git
monitor_speed = 115200